### PR TITLE
Setup

### PR DESCRIPTION
**Pull request by solisa986**
# Setup and Testing

## Description

Added the testing files and the setup.fy file.

### Type of Change

- [X] Feature
- [ ] Bug fix
- [ ] Documentation

## Contributors

- @solisa986 

## Reminder

All GitHub Actions should be in a passing state before any pull request is merged.

### CODE REVIEW

**Review by RyanHiltyAllegheny — APPROVED** [review]
Adjustments needed to setup and complete test coverage process

**Review by caldwella2 — DISMISSED** [review]
we need these test cases

**Review by rachaelharris — DISMISSED** [review]
merge conflicts fixed

**Review by caldwella2 — APPROVED** [review]
this should fix linting errors

**Review by rachaelharris — APPROVED** [review]
happy to see the linting errors fixed

**Review by RyanHiltyAllegheny — APPROVED** [review]
All checks passes for testing setup

**Pull request merged**
