### PR TITLE
Update py_counter.py

### PR DESCRIPTION
**Pull request by guzmanr04**
# Your Title Function Count

## Description

Count the number of classes

### Type of Change

- [x] Feature
- [ ] Bug fix
- [ ] Documentation

## Contributors

- @

## Reminder

All GitHub Actions should be in a passing state before any pull request is merged.

### CODE REVIEW

**Review by solisa986 — DISMISSED** [review]
looks promising

**Review by caldwella2 — APPROVED** [review]
good function sir

**Review by solisa986 — APPROVED** [review]
love it

**Review by caldwella2 — APPROVED** [review]
fixed error

**Pull request merged**
